#!/bin/sh

### BEGIN INIT INFO
# Provides:          redis
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts redis database system
# Description:       starts redis using basic start scripts
### END INIT INFO

{% if port %}
PORT={{ port }}
{% else %}
PORT=6379
{% endif %}

PATH=/opt/redisnotice/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME="redis$PORT"
DAEMON=/opt/redisnotice/bin/redis-server
CONF="/opt/redisnotice/${PORT}.conf"

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "

        start-stop-daemon --start --user redis -c redis:redis \
            --startas $DAEMON -- $CONF 

        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "

        start-stop-daemon --stop --exec $DAEMON -c redis:redis \
            $DAEMON -- $CONF

        echo "$NAME."
        ;;
      *)    
            N=/etc/init.d/$NAME$PORT
            echo "Usage: $N {start|stop}" >&2
            exit 1
            ;;
    esac
    
    exit 0
